### ISSUE TITLE
Add Tweet button beside Tweet quote

### ISSUE THREAD

**Issue by janreggie** [janreggie/randomquoter#3]
Font Awesome has a [Twitter icon](https://fontawesome.com/v4.7.0/icon/twitter) that you can use and import.

**Comment by rarchitgupta** [comment]
I'd like to take this up. Just to be clear. I just place a tweet icon right next to the Tweet text inside the button?

**Comment by janreggie** [comment]
Yeah, preferably on the left side before the "Tweet Quote" message. Assigning this to you!

**Comment by janreggie** [comment]
Resolved by #4. Thanks again @rarchitgupta
